apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-inter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-inter
  template:
    metadata:
      labels:
        app: ai-inter
    spec:
      containers:
        - name: ai-inter
          image: chad0/ai-inter:updated  
          imagePullPolicy: Always 
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-inter-service
  labels:
    app: ai-inter-service
spec:
  type: LoadBalancer
  selector:
    app: ai-inter
  ports:
    - name: http-metrics
      port: 80
      targetPort: 5000
